---

- name: Update apt
  apt: update_cache=yes

- name: Install php5
  apt: name={{ item }} state=installed
  with_items:
   - apache2

- name: Install php5 
  apt: name={{ item }} state=installed
  with_items:
   - php5

- name: Template php.ini
  template: src=php.ini dest=/etc/php5/apache2/php.ini



